[package]
name = "wastebin"
version = "1.1.0"
edition = "2021"

[dependencies]
askama = { git = "https://github.com/djc/askama", features = ["with-axum"] }
askama_axum = { git = "https://github.com/djc/askama" }
axum = { version = "0.5", features = ["json"] }
bytes = "1"
lru = "0"
once_cell = "1"
rand = "0"
rusqlite = { version = "0.27", features = ["bundled"] }
rusqlite_migration = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "html", "plist-load", "regex-fancy"] }
thiserror = "1"
time = { version = "0.3", features = ["macros", "serde"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0", features = ["compression-br", "compression-deflate", "compression-gzip", "timeout", "trace"] }
tracing = "0"
tracing-subscriber = "0"
