name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.70.0
      with:
        components: clippy
    - run: cargo clippy -- -W clippy::pedantic
    - run: cargo test
